name: 'Run Tests'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - v2-refactoring

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Setup Node Environment'
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm run coverage
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          # 
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN  }}
